// Rotated by LoadingBasketballs every 2.5s (feature request, 2026-10-06)
// instead of a single static "Loading X" label. All basketball/fantasy-
// league themed, gerund-phrase style, matching the user's own examples
// ("Bouncing the balls", "Connecting the dots", "Fantasizing").
export const LOADING_PHRASES: string[] = [
  "Bouncing the balls",
  "Connecting the dots",
  "Fantasizing",
  "Crunching the numbers",
  "Boxing out the lag",
  "Draining threes",
  "Posting up the data",
  "Running the fast break",
  "Setting the screen",
  "Calling the timeout",
  "Checking the box score",
  "Subbing in the stats",
  "Drafting the rookies",
  "Working the trade wire",
  "Benching the bugs",
  "Reviewing the tape",
  "Spinning the rock",
  "Dribbling through traffic",
  "Finding the open man",
  "Clearing the boards",
  "Sinking the free throws",
  "Measuring the vertical",
  "Tracking the turnovers",
  "Updating the standings",
  "Shuffling the lineup",
  "Scouting the waiver wire",
  "Counting the assists",
  "Weighing the ratings",
  "Syncing the scoreboard",
  "Warming up the bench",
  "Calling the alley-oop",
  "Taping the ankles",
  "Icing the shoulder",
  "Watching the replay",
  "Setting the pick",
  "Boxing out for the rebound",
  "Tallying the triple-doubles",
  "Polishing the trophy",
  "Refreshing the rankings",
  "Loading the locker room",
  "Lacing up the sneakers",
  "Chalking the hands",
  "Huddling up",
  "Breaking the press",
  "Finding the mismatch",
  "Re-running the numbers",
  "Buffing the box score",
  "Spotting up for three",
  "Rotating on defense",
  "Nothing but net",
];
